lib/asitext_web/router.ex
defmodule AsitextWeb.Router do
  use AsitextWeb, :router
  use Plug.ErrorHandler

  pipeline :browser do
    plug :accepts, ["html", "json"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :atom do
    plug :accepts, ["xml"]
    plug :fetch_session
  end

  pipeline :manifest do
    plug :accepts, ["json"]
  end

  scope "/", AsitextWeb do
    pipe_through :atom

    get "/all.xml", PageController, :atom
    get "/xml/:type", PageController, :atom_type
    get "/xml/themes/:slug", PageController, :atom_themes
    get "/xml/authors/:slug", PageController, :atom_authors
    get "/xml/chroniques/:slug", PageController, :atom_chronicles
  end

  scope "/", AsitextWeb do
    pipe_through :manifest

    get "/manifest.json", ManifestController, :manifest
  end

  scope "/", AsitextWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    # old routes of the arretsurimages site
    get "/contenu.php", PageController, :find_and_redirect
    get "/vite.php", PageController, :find_and_redirect
    get "/dossier.php", PageController, :find_and_redirect

    # Normal routes
    get "/login", PageController, :login
    post "/login", PageController, :log
    post "/logout", PageController, :logout
    get "/search", PageController, :search
    get "/authors", PageController, :authors
    get "/authors/:slug", PageController, :author
    get "/themes", PageController, :themes
    get "/themes/:slug", PageController, :theme
    get "/dossiers", PageController, :folders
    get "/dossiers/:slug", PageController, :folder

    get "/blogs", PageController, :redirect_blogs
    get "/blogs/:slug", PageController, :redirect_blog

    get "/chroniques", PageController, :chronicles
    get "/chroniques/:slug", PageController, :chronicle

    get "/:type/", PageController, :type
    get "/:type/:slug", PageController, :show
    get "/:type/:slug/comments", PageController, :comments
    get "/:type/:list/:slug", PageController, :show
    get "/:type/:list/:slug/comments", PageController, :comments
  end

  defp handle_errors(conn, %{kind: kind, reason: reason, stack: stacktrace}) do
    conn = conn
    |> Plug.Conn.fetch_query_params()

    params =
    for {key, _value} = tuple <- conn.params, into: %{} do
      if key in ["password", "password_confirmation"] do
        {key, "[FILTERED]"}
      else
        tuple
      end
    end

    occurrence_data = %{
      "request" => %{
        "url" => "#{conn.scheme}://#{conn.host}:#{conn.port}#{conn.request_path}",
        "user_ip" => List.to_string(:inet.ntoa(conn.remote_ip)),
        "headers" => Enum.into(conn.req_headers, %{}),
        "method" => conn.method,
        "params" => params,
      }
    }

    Rollbax.report(kind, reason, stacktrace, _custom_data = %{}, occurrence_data)
  end
end

lib/asitext_web/views/layout_view.ex
defmodule AsitextWeb.LayoutView do
  use AsitextWeb, :view

  def nav_links do
    [
      {"articles", "Articles"},
      {"emissions", "Émissions"},
      {"chroniques", "Chroniques"},
    ]
  end
end

lib/asitext_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= AsitextWeb.PageView.title_cleanup(@title) %> - ASI Lite</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="shortcut icon" href="<%= static_path(@conn, "/images/favicon.png") %>">
    <link rel="manifest" href="<%= manifest_path(@conn, :manifest) %>">
    <link href="<%= page_path(@conn, :atom) %>" rel="alternate" title="Tout les contenus" type="application/atom+xml">
    <%= for {type, name} <- nav_links() do %>
      <link href="<%= page_path(@conn, :atom_type, type) %>" rel="alternate" title="<%= name %>" type="application/atom+xml">
    <% end %>
    <%= render_existing @view_module, "header."<> @view_template, assigns %>
    <%= render_existing @view_module, "header."<> (assigns[:header_template] || ""), assigns %>
    <script async defer data-domain="asi.2metz.fr" src="https://plausible.io/js/plausible.js"></script>
  </head>

  <body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= page_path(@conn, :index) %>">ASI Lite</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <%= for {type, name} <- nav_links() do %>
              <li<%= if assigns[:type] && @type == type do %> class="active"<% end %>><a href="<%= page_path(@conn, :type, type) %>"><%= name %></a></li>
            <% end %>
          </ul>
          <form class="navbar-form navbar-left" action="<%= page_path(@conn, :search) %>" method="get">
            <div class="form-group">
              <input type="text" name="q" size="15" value="<%= assigns[:q] || "" %>" class="form-control" placeholder="Recherche">
            </div>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= if (@conn.assigns[:logged]) do %>
                <%= form_for @conn, page_path(@conn, :logout), [class: "navbar-form no-padding-right"], fn _f -> %>
                  <%= submit "Déconnexion", class: "btn btn-default" %>
                <% end %>
              <% else %>
                <a href="<%= page_path(@conn, :login) %>">Connexion</a>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= unless (@conn.assigns[:logged]) do %>
        <p class="alert alert-info" role="alert">Pour accéder à la totalité du contenu vous devez vous connecter avec vos identifiants à Arrêt sur Images.
          <br>
          Pour des raisons de sécurité cet accès est restreint pour le moment. Demandez la procédure à <a href="https://twitter.com/francois2metz">l'auteur, François</a>.
        </p>
      <% end %>

      <main>
        <%= render @view_module, @view_template, assigns %>
      </main>

      <br>

      <footer>
        <p>
          <a href="<%= page_path(@conn, :folders) %>">Dossiers</a> -
          <a href="<%= page_path(@conn, :themes) %>">Thèmes</a> -
          <a href="<%= page_path(@conn, :authors) %>">Auteurs</a>
        </p>
        <p>Ce site <a href="https://github.com/francois2metz/asilite">open-source</a> affiche les contenus d'<a href="https://arretsurimages.net/">Arrêt sur images</a> d'une manière optimisé sur mobile. Non affilié à <a href="https://arretsurimages.net/">Arrêt sur images</a>. Créé par <a href="https://twitter.com/francois2metz">@francois2metz</a>. Voici la <a href="/api.html">documentation de l'API</a>.</p>
      </footer>

    </div> <!-- /container -->
    <script nonce="<%= @conn.assigns[:nonce] %>">
      var classChildren = function classChildren(x) {
          return document.getElementsByClassName('navbar-' + x)[0];
      };

      classChildren('toggle').addEventListener('click', function () {
          classChildren('collapse').classList.toggle('collapse');
      }, false);
    </script>
  </body>
</html>